### ISSUE TITLE
da se napiše angleški tekst za žar brez utvar

### ISSUE THREAD

**Issue by muki** [danesjenovdan/danesjenovdan.si-en#2]
zgled tukaj: https://github.com/danesjenovdan/danesjenovdan.si/issues/27

**Comment by cylebrity** [comment]
**_replace_** Reaction to another showing of the emperor's new clothes or Why Pahor is a bad president. Instead of a TV roast, we lit a fire with a content critique. Roast status: finished!
**_with_** Yet another manifestation of the emperor's lack of clothing, or, Why Pahor is a lousy president. Rather than "enjoying" the pacifying TV roast, we lit the fire by engaging in substantial critique of his work. The internet then did the rest. Roast status: finished!

**_replace_** Roast without pretense
**_with_**  Kosher roast

**_replace_**
February 14, 2016 was not only the day of the annual commercialization of love, but also of the president. Broadcast on commercial television on this day was a Roast featuring Borut Pahor. Due to the guest, the show's format felt watered down and effectively turned in to a start of a new political campaign. On this occasion, we at DJND turned the attention away from the adorable mischief and on to Pahor's political mistakes. The position of President is important and requires serious critique: We took him from the TV roast and put him in an internet oven that left him significantly more scorched.
**_with_**
On February 14, 2016, we did not just celebrate the commodification of love, but also of our president himself. We sat in awe and watched the TV Roast featuring Borut Pahor, complaining not only about bad TV, but also about the quality of the president's work. Because of the important guest, the show's format felt watered down and effectively turned in to a start of a new political campaign. We at DJND decided to turn the attention away from the adorable TV mischief and on to Pahor's political mistakes. In Slovenia, presidency in mainly a symbolic function, and one that supposedly carries with it moral excellency. As the figure of the president is very important to the people, it also requires serious critique. So, we took him from the benign TV roast and put him in an internet oven that left him significantly more scorched.
